---
title: "passwrods"
author: "Shuhan Song"
date: "1/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
library(tidyverse)
```

```{r}
passwords <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-14/passwords.csv')
```

```{r}
head(passwords)
```

```{r}
# exploring dataset
summary(passwords)
count(passwords, category) %>% arrange(desc(n))

filter(passwords, category == "name") %>% arrange(desc(strength))

strongest_pw <- filter(passwords, strength == 10) 
```

```{r}
passwords_n_3_category <- passwords %>% 
  filter(category %in% c("name", "cool-macho", "simple-alphanumeric")) %>% 
  filter(strength %in% c(1, 10))
```

```{r}
name_pw <- passwords_n_3_category %>% 
  filter(category == "name")

ggplot(name_pw, aes(x = fct_reorder(password, strength), y = rank)) +
  geom_col(aes(fill = strength)) +
  coord_flip()
```


### parse character
```{r}
passwards_char <- passwords %>% 
```

