---
title: "adoptable dogs"
author: "Shuhan Song"
date: "12/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(janitor)
library(sf)
library(here)
```


```{r}
# Get the Data

dog_moves <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-12-17/dog_moves.csv')

dog_travel <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-12-17/dog_travel.csv') 

dog_descriptions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-12-17/dog_descriptions.csv')

```

# What dogs are waiting to be adopted?

```{r, include=FALSE}
head(dog_descriptions)
```
mixed vs. pure
```{r}
dog_breed_mixed <- dog_descriptions %>% 
  filter(breed_unknown == FALSE) %>% 
  count(breed_mixed) %>% 
  mutate(pct = round(n/sum(n), 2))

ggplot(data = dog_breed_mixed,
       aes(x = "", y = n, fill = breed_mixed)) +
  geom_bar(alpha = 0.75, 
           width = 1, 
           stat = "identity", 
           show.legend = FALSE) +
  coord_polar("y", start=0) +
  scale_fill_manual(values=c("#E69E00", "#56B4C9")) +
  #or scale_fill_brewer(palette="Dark2") +
  geom_text(aes(y = 50000), label = "Pure (29%)", size = 4) +
  geom_text(aes(y = 20000), label = "Mixed (71%)", size = 4) +
  labs(x = "",
       y = "Mixed breeded or not?",
       caption = "Mixeded breeded (n = 41591) vs. pure (n = 16589)") +
  theme_minimal() +
  theme(axis.text.x=element_blank())
```

```{r, eval=FALSE}
ggsave(here("figure", "breeding types.jpg"))
```

female vs. male

```{r}
dog_sex <- dog_descriptions %>% 
  filter(sex != "Unknown") %>% 
  count(sex) %>% 
  mutate(pct = round(n/sum(n), 2))
```

```{r}
ggplot(data = dog_sex,
       aes(x = "", y = n, fill = sex)) +
  geom_bar(alpha = 0.7, 
           width = 1, 
           stat = "identity", 
           show.legend = FALSE) +
  coord_polar("y", start=0) +
  scale_fill_manual(values=c("#A690A0", "#A0B469")) +
  #or scale_fill_brewer(palette="Dark2") +
  geom_text(aes(y = 43000), label = "Female (48%)", size = 4) +
  geom_text(aes(y = 15000), label = "Male (52%)", size = 4) +
  labs(x = "",
       y = "Females or males?",
       caption = "Female (n = 27883) vs. male (n = 30294)") +
  theme_minimal() +
  theme(axis.text.x=element_blank())

```

```{r, eval=FALSE}
ggsave(here("figure", "dogs' sex.jpg"))
```

age?

```{r}
dog_age <- dog_descriptions %>%  
  count(age) %>% 
  mutate(pct = round(n/sum(n), 2))
```

```{r}
ggplot(data = dog_age,
       aes(x = "", y = n, fill = age)) +
  geom_bar(alpha = 0.75, 
           width = 1, 
           stat = "identity", 
           show.legend = FALSE) +
  coord_polar("y", start=0) +
  scale_fill_manual(values=c("#56B4C9", "#9071FF", "#889E0F", "#FFBF60")) +
  #or scale_fill_brewer(palette="Dark2") +
  geom_text(aes(y = 43000), label = "Adult (48%)", size = 4) +
  geom_text(aes(y = 25000), label = "Baby (16%)", size = 4) +
  geom_text(aes(y = 18000), label = "Senior (8%)", size = 4) +
  geom_text(aes(y = 10000), label = "Young (28%)", size = 4) +
  labs(x = "",
       y = "How old are the dogs?",
       caption = "Baby (n = 9397), young (n = 16194), adult (n = 27955), senior (n = 4634)") +
  theme_minimal() +
  theme(axis.text.x=element_blank())
```

```{r, eval=FALSE}
ggsave(here("figure", "how old are the dogs.jpg"))
```

# Where are the dogs?

```{r total map}
state_loc <- data.frame("state" = state.name,
                        "long" = state.center$x,
                        "lat" = state.center$y) %>% 
  filter(state != "Alaska") %>% 
  filter(state != "Hawaii")

dog_moves_us <- dog_moves %>% 
  filter(inUS == TRUE) %>% 
  rename(state = location) %>% 
  left_join(state_loc, by = "state") %>% 
  drop_na(long, lat)

dog_moves_us <- st_as_sf(dog_moves_us, coords = c('long', 'lat'))

st_crs(dog_moves_us) <- 4326


states_polygon <- map_data("state")

myPalette <- colorRampPalette(c("cyan", "#007FFF","#FFBF00", "orange", "red"))

ggplot() +
  geom_polygon(data = states_polygon,
               mapping = aes(x = long, y = lat,
                             group = group),
               fill = "white",
               color = "gray70",
               size = 0.3) +
  geom_sf(data = dog_moves_us,
          aes(color = total),
          size = 3,
          alpha = 0.6) +
  scale_color_gradientn(colors = myPalette(2.7)) +
  theme_void() +
  labs(color = "Total number of \nadoptable dogs")
```

```{r, eval=FALSE}
ggsave(here("figure", "total number of adoptable dogs.jpg"))
```

```{r, include=FALSE}
dog_moves_outside_us <- dog_moves %>% 
  filter(inUS == FALSE)

summary(dog_moves_outside_us)

# lack of data outside US
```

# Where are dogs found?

```{r, include=FALSE}
head(dog_travel)
unique(dog_travel$found)
length(dog_travel$found)
```

```{r}
dog_found_30 <- dog_travel %>% 
  count(found) %>% 
  arrange(desc(n)) %>% 
  head(30)

dog_found_30[3, 1] <- "Virginia"

dog_found_30[4, 1] <- "North Carolina"

dog_found_30[5, 1] <- "Maryland"

dog_found_30[15, 1] <- "New Jersey"

dog_found_30[22, 1] <- "US"

dog_found_30[24, 1] <- "Seattle"

dog_found_10 <- dog_found_30 %>% 
  filter(!found %in% c("US", "Lab Rescue LRCP", "Puerto Rico")) %>% 
  group_by(found) %>% 
  summarize(n = sum(n)) %>% 
  arrange(desc(n)) %>% 
  head(10)
```

```{r}
ggplot(data = dog_found_10, 
       aes(x = fct_reorder(found, n), 
           y = n)) +
  geom_col(aes(fill = found),
           width = 0.6,
           show.legend = FALSE) +
  scale_fill_brewer(type = "qual", palette = 3) +
  coord_flip() +
  theme_minimal(base_line_size = 0.35) +
  labs(x = "US State", y = "",
       title = "Numbers of dogs found in top 10 states")
```

```{r, eval=FALSE}
ggsave(here("figure", "numbers of dogs found in top 10 states.jpg"))
```


