---
title: "Australia fires"
author: "Shuhan Song"
date: "1/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, include = FALSE)
```

```{r}
library(tidyverse)
library(mapview)
library(sf)
library(here)
```

### Map the Australia fires

Method based on [link](https://gist.github.com/deanmarchiori/cb64f105eb0f6204eaa88323eaa29fdb) by Dean Marchiori

```{r}

url <- "http://www.rfs.nsw.gov.au/feeds/majorIncidents.json"

fires <- st_read(url)

fire_poly <- fires %>% 
  st_buffer(dist = 0) %>% 
  st_union(by_feature = TRUE)
```

```{r, include=TRUE}
mapview(fire_poly, legend = FALSE, col.regions = "red", color = "gray")
```

```{r}
# Get the Data

rainfall <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-07/rainfall.csv')
temperature <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-07/temperature.csv')

```

```{r}
#head(arrange(rainfall, desc(rainfall)))
```

```{r}
count(temperature, date)

temperature$city_name <- taxize::taxize_capwords(tolower(temperature$city_name))
head(temperature)
```


```{r}
count(rainfall, station_name, lat)
head(rainfall)
```

```{r}
max_temperature <- temperature  %>% 
  group_by(city_name, temp_type) %>% 
  summarize(mean = round(mean(temperature, na.rm = TRUE), 2)) %>% 
  group_by(city_name) %>% 
  mutate(city_mean = round(mean(mean), 2))

temperature_clean_date <- temperature %>% 
  separate(date, c("year", "month", "day"))

temperature_annual <- temperature_clean_date %>% 
  group_by(city_name, year, temp_type)%>% 
  summarize(mean = round(mean(temperature, na.rm = TRUE), 2)) %>% 
  group_by(city_name, year) %>% 
  mutate(city_annual_mean = round(mean(mean), 2))

temperature_2019 <- temperature_annual %>% 
  filter(year == "2019")

temperature_2019_month <- temperature_clean_date %>% 
  filter(year == "2019") 
```

### Temperature 2010-2019

```{r, include=TRUE}
ggplot() +
  geom_point(temperature_annual, 
       mapping = aes(x =as.numeric(year), y = city_annual_mean, color = city_name), 
       alpha = 0.2) +
  geom_line(temperature_annual, 
       mapping = aes(x =as.numeric(year), y = city_annual_mean, color = city_name), 
       alpha = 0.35) +
  geom_point(temperature_2019, 
       mapping = aes(x = as.numeric(year), y = city_annual_mean, color = city_name), 
       alpha = 1) +
  geom_curve(aes(x = 2017.6, y = 23.8, xend = 2018.8, yend = 23.6),
             size = 0.3,
             curvature = -0.4,
             arrow = arrow(length = unit(0.02, "npc"))) +
  geom_text(aes(x = 2017.5, y = 23.5, label = "The extreme high temperature (Jan-May) \nlead to the worst fire season of Australia \nin 20 years begun in September 2019"),
            size = 2.5,
            hjust = 1) +
  geom_text(aes(x = 2010.1, y = 11.5, label = "Fires across the country have scorched millions of acres of land \nwhere homes were destoryed and people were killed (Popovich, 2020)"),
            size = 2.5,
            hjust = 0) +
  scale_x_continuous(limits = c(2010, 2019), breaks = c(2010, 2013, 2016, 2019)) + 
  scale_y_continuous(limits = c(10, 25)) +
  labs(x = "Year", 
       y = "Mean temperature (Celsius)", 
       color = "Cities in Australia",
       caption = "Data source: Bureau of Meterology Climate Data Online.") +
  theme_minimal() 
```

```{r}
ggsave(here("figure", "annual_temperature.jpg"), width = 6, height = 6)
```

### Rainfall 2001-2019

```{r}
rainfall_annual <- rainfall %>% 
  group_by(city_name, year)%>% 
  summarize(mean = round(mean(rainfall, na.rm = TRUE), 2))

rainfall_2019 <- rainfall_annual %>% 
  filter(year %in% c("2017", "2018", "2019"))
```

```{r, include=TRUE}
ggplot() +
  geom_point(rainfall_annual, 
       mapping = aes(x =as.numeric(year), y = mean, color = city_name), 
       alpha = 0.3) +
  geom_line(rainfall_annual, 
       mapping = aes(x =as.numeric(year), y = mean, color = city_name), 
       alpha = 0.3) +
  geom_line(rainfall_2019, 
       mapping = aes(x =as.numeric(year), y = mean, color = city_name), 
       alpha = 0.6) +
  geom_point(rainfall_2019, 
       mapping = aes(x = as.numeric(year), y = mean, color = city_name), 
       alpha = 1) +
  scale_x_continuous(limits = c(2001, 2019), breaks = c(2001, 2004, 2007, 2010, 2013, 2016, 2019)) +
  theme_minimal() +
  scale_color_brewer(palette = "Dark2", direction = -1) +
  labs(x = "Year", 
       y = "Mean rainfall (mm)", 
       color = "Cities in Australia",
       caption = "Data source: Bureau of Meterology Climate Data Online.") +
  geom_curve(aes(x = 2018.5, y = 4.5, xend = 2018, yend = 3),
             size = 0.3,
             curvature = -0.25,
             arrow = arrow(length = unit(0.02, "npc"))) +
  geom_text(aes(x = 2018.9, y = 5, label = "Rainfall has been\nlow since 2017"),
            size = 2.5,
            hjust = 1) +
  theme(panel.grid.minor = element_blank())
```

```{r}
ggsave(here("figure", "annual_rainfall.jpg"), width = 7, height = 5)
```


Reference: 

Popovich, N., Lu, D., & Migliozzi, B. (2020, January 9). See Where Australia’s Deadly Wildfires Are Burning. The New York Times. https://www.nytimes.com/interactive/2020/01/02/climate/australia-fires-map.html
